baseURL = "https://tonbridgemakerspace.com/"
languageCode = "en-gb"
title = "Tonbridge Makerspace"
theme = "ananke"
summaryLength = 42
SectionPagesMenu = "main"

[params]
  site_logo = "images/TMS_Castle.svg"
  ananke_socials = [{name = "instagram", url = "https://www.instagram.com/tonbridgemakerspace/"}, {name = "rss", url = "/index.xml"}]